name: Deploy PR previews

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        if: github.event.action != 'closed'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install node modules
        if: github.event.action != 'closed'
        run: npm ci

      - name: Upload images to Cloudinary
        if: github.event.action != 'closed'
        run: npm run images:upload
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

      - name: Build Next.js site
        if: github.event.action != 'closed'
        env:
          NEXT_PUBLIC_BASE_PATH: /pr-preview/pr-${{ github.event.number }}
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        run: npm run build

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./out
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          pages-base-url: marcchen.github.io
          action: auto